# Generated by Django 4.0.4 on 2022-04-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qr_img',
            field=models.ImageField(blank=True, upload_to='static/media'),
        ),
    ]
